FROM node:24 AS builder

WORKDIR /usr/src/app

COPY ./gateway/package*.json ./
RUN npm install

COPY ./gateway .
COPY ./proto ./proto

RUN npm run build

FROM node:24-alpine

WORKDIR /usr/src/app
COPY --from=builder /usr/src/app ./

CMD ["npm", "run", "start:prod"]
